### ISSUE TITLE
No highlighting at latest VS code version

### ISSUE THREAD

**Issue by sergei-kashlikov** [TheNetAdmin/vscode-linkerscript#4]
It seems like highlighting is no more working after some latest VS code update. Only comments are green.

**Comment by TheNetAdmin** [comment]
Would you show me a screenshot of the highlighting issue, and the vscode version you are using?

**Comment by sergei-kashlikov** [comment]
This is the start of my file, rest of it is the same:
![image](https://user-images.githubusercontent.com/66557275/178123385-f576236e-7472-488c-97ac-4f6e88bce8b5.png)

Version: 1.69.0 (user setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by TheNetAdmin** [comment]
This is a funny problem. After debugging it for a while, I found the vscode-linkerscript plugin is actually working but the problem is vscode's color theme:

If I use the `Dark (Visual Studio - C/C++)` theme, the highlights are just like what you saw:

![image](https://user-images.githubusercontent.com/18525442/179339681-3d4f19ab-54ed-4545-ae4a-3cc1f27ac0c9.png)

Once I change to another color theme, say `Monokai`, the highlights work fine:

![image](https://user-images.githubusercontent.com/18525442/179339698-fd674984-11ad-4714-a779-e9df05fd50c6.png)

My guess is 1.69.0 vscode has broken some color themes... At this point, I don't really know how to fix the color themes. Maybe you can post an issue to vscode repo, and reference our current issue, to see if vscode developers have clues?

**Comment by TheNetAdmin** [comment]
Seems inactive from the upstream repo issue, closing this issue and feel free to reopen it if necessary.
